version: '3.3'

services:
  backoffice:
    image: {{ image.repository }}:{{ image.tag }}    
    networks:
      - app
      - mon
    deploy:
      labels:
        - "swarm-sync.managed=true"
        - "swarm-sync.image-pattern={{ image.tag_pattern }}"
      restart_policy:
        condition: on-failure
        window: 120s
      replicas: 1
      placement:
        constraints:
          - node.labels.worker == true
      resources:
        reservations:
          memory: 128M
networks:
  mon:
    external: true  
  app:
    external: true
